### PR TITLE
Support Symfony 3.0

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by matthiasnoback** [comment]
Thanks for helping out! I'm afraid there's a bit more to it though, see the failing unit tests on Travis. If you get a chance to work on this, feel free to do so. Also, I'd like to test both a current 2.\* version and 3.0 on Travis, to make sure that both keep working (see for an over the top example https://github.com/matthiasnoback/symfony-service-definition-validator/blob/master/.travis.yml). If you don't have time to fix it, I'll do it, but a bit later.

**Comment by ruudk** [comment]
Like this? It seems that some early symfony releases are not supported. Should we update the composer.json and remove the Travis tests?

**Comment by ruudk** [comment]
KernelTestCase was introduced in Symfony 2.5.

**Comment by matthiasnoback** [comment]
Thanks for your work, just merged and released. Will now merge your other fixes.

**Pull request merged**
